name: testpauld
favicon: null
layout_spectrum: 0.18460912071168423
typography_spectrum: 0.22851201053708792
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.8810147759504616
  lightness: 0.045359236653894186
  saturation: 0.794877426000312
  rhythmicContrast: 0.4062684855889529
purpose: []
